Repository NDCLab/baseEEG, pull requests merged in 2021-05, with the labels that each got.

#97 Segmentation Module
  .gitignore
  base_eeg/segment.py
Labels: enhancement

#96 Interpolation Module
  .gitignore
  base_eeg/interp.py
Labels: documentation, enhancement

#116 Refactored segment for pipeline integration
  base_eeg/interp.py
Labels: enhancement

#114 Refactored segment for pipeline integration
  base_eeg/segment.py
Labels: enhancement

#115 Refactored final-reject for pipeline integration
  base_eeg/finalRej.py
  base_eeg/test.py
Labels: enhancement

#117 Created issues template
  .github/ISSUE_TEMPLATE/---agenda.md
  .github/ISSUE_TEMPLATE/---bug-report.md
  .github/ISSUE_TEMPLATE/---documentation-request.md
  .github/ISSUE_TEMPLATE/---feature-request.md
  .github/ISSUE_TEMPLATE/--test-request.md
Labels: documentation

#101 Simple function to collate all dictionaries and write to disk
  base_eeg/dictCollat.py
Labels: enhancement
